name: whisp
description: "Demo application for mrumru."
publish_to: 'none'
version: 0.0.3

environment:
  sdk: "3.2.6"
  flutter: "3.16.9"

dependencies:
  flutter:
    sdk: flutter

  # Data Over Audio
  mrumru:
    git:
      url: git@github.com:snggle/mrumru.git
      ref: dev

  # A package that allows you to use the native file explorer to pick single or multiple files, with extensions filtering support.
  # https://pub.dev/packages/file_picker
  file_picker: 8.0.0

  # Draw SVG files using Flutter.
  # https://pub.dev/packages/flutter_svg
  flutter_svg: 2.0.10+1

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: 8.1.6

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.4.0

  # A package that provides an easy way to add particles animation in Flutter project.
  # https://pub.dev/packages/particles_flutter
  particles_flutter: 1.0.1

  # A comprehensive, cross-platform path manipulation library for Dart.
  # https://pub.dev/packages/path
  path: 1.8.3

  # A Flutter plugin for finding commonly used locations on the filesystem.
  # https://pub.dev/packages/path_provider
  path_provider: 2.1.4

  # Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  # https://pub.dev/packages/permission_handler
  permission_handler: 11.0.1

  # A library to get Audio Devices on Windows.
  # https://pub.dev/packages/win32audio
  win32audio: 1.4.0

  # This plugin allows Flutter desktop apps to resizing and repositioning the window.
  # https://pub.dev/packages/window_manager
  window_manager: 0.4.3

  # A Flutter plugin to share content from your Flutter app via the platform's share dialog.
  # https://pub.dev/packages/share_plus
  share_plus: 7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/blue_cloud_anim.webp
    - assets/blue_cloud.png
    - assets/cream_cloud_anim.webp
    - assets/cream_cloud.png
    - assets/snggle_face.gif
    - assets/dice-1.svg
    - assets/dice-2.svg
    - assets/dice-3.svg
    - assets/dice-4.svg
    - assets/dice-5.svg
    - assets/dice-6.svg
  fonts:
    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam-Bold.ttf
